/* tslint:disable */
/* eslint-disable */
/**
 * Requirement Clarify Manager API
 * 요구사항 명세 관리 시스템 (Requirement Clarify Manager) MVP API 사양서. 기획자가 마크다운 파일이나 텍스트로 요구사항을 등록하면, 시스템이 데이터 사전을 추출 및 질의 과정을 거쳐 최종적으로 Event Storming 분석 결과를 시각화하여 제공합니다. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AnalysisViewResponse
 */
export interface AnalysisViewResponse {
    /**
     * 
     * @type {AnalysisViewResponseRequirement}
     * @memberof AnalysisViewResponse
     */
    'requirement'?: AnalysisViewResponseRequirement;
    /**
     * 
     * @type {Array<object>}
     * @memberof AnalysisViewResponse
     */
    'dataDictionary'?: Array<object>;
    /**
     * 
     * @type {AnalysisViewResponseEventStorming}
     * @memberof AnalysisViewResponse
     */
    'eventStorming'?: AnalysisViewResponseEventStorming;
    /**
     * 
     * @type {AnalysisViewResponseDiagrams}
     * @memberof AnalysisViewResponse
     */
    'diagrams'?: AnalysisViewResponseDiagrams;
}
/**
 * 
 * @export
 * @interface AnalysisViewResponseDiagrams
 */
export interface AnalysisViewResponseDiagrams {
    /**
     * 
     * @type {string}
     * @memberof AnalysisViewResponseDiagrams
     */
    'businessProcess'?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisViewResponseDiagrams
     */
    'sequenceDiagram'?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisViewResponseDiagrams
     */
    'usecaseDiagram'?: string;
}
/**
 * 
 * @export
 * @interface AnalysisViewResponseEventStorming
 */
export interface AnalysisViewResponseEventStorming {
    /**
     * 
     * @type {Array<string>}
     * @memberof AnalysisViewResponseEventStorming
     */
    'actors'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AnalysisViewResponseEventStorming
     */
    'domainEvents'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AnalysisViewResponseEventStorming
     */
    'commands'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AnalysisViewResponseEventStorming
     */
    'domainObjects'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AnalysisViewResponseEventStorming
     */
    'aggregates'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AnalysisViewResponseEventStorming
     */
    'externalSystems'?: Array<string>;
}
/**
 * 
 * @export
 * @interface AnalysisViewResponseRequirement
 */
export interface AnalysisViewResponseRequirement {
    /**
     * 
     * @type {string}
     * @memberof AnalysisViewResponseRequirement
     */
    'requirementNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalysisViewResponseRequirement
     */
    'originalFileUrl'?: string;
}
/**
 * 
 * @export
 * @interface ApiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost200Response
 */
export interface ApiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost200Response
     */
    'updated'?: boolean;
    /**
     * 
     * @type {PendingTermResponse}
     * @memberof ApiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost200Response
     */
    'nextPendingTerm'?: PendingTermResponse;
}
/**
 * 
 * @export
 * @interface ApiV1RequirementsIdStatusPatch200Response
 */
export interface ApiV1RequirementsIdStatusPatch200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiV1RequirementsIdStatusPatch200Response
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1RequirementsIdStatusPatch200Response
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1RequirementsIdStatusPatch200Response
     */
    'updatedAt'?: string;
}
/**
 * 
 * @export
 * @interface ApiV1RequirementsIdStatusPatchRequest
 */
export interface ApiV1RequirementsIdStatusPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1RequirementsIdStatusPatchRequest
     */
    'status': ApiV1RequirementsIdStatusPatchRequestStatusEnum;
}

export const ApiV1RequirementsIdStatusPatchRequestStatusEnum = {
    Draft: 'Draft',
    Clarifying: 'Clarifying',
    Clarified: 'Clarified',
    InProgress: 'In Progress',
    Done: 'Done'
} as const;

export type ApiV1RequirementsIdStatusPatchRequestStatusEnum = typeof ApiV1RequirementsIdStatusPatchRequestStatusEnum[keyof typeof ApiV1RequirementsIdStatusPatchRequestStatusEnum];

/**
 * 
 * @export
 * @interface AsyncJobResponse
 */
export interface AsyncJobResponse {
    /**
     * 
     * @type {string}
     * @memberof AsyncJobResponse
     */
    'jobId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AsyncJobResponse
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof AsyncJobResponse
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface ClarifyRequest
 */
export interface ClarifyRequest {
    /**
     * 
     * @type {string}
     * @memberof ClarifyRequest
     */
    'action': ClarifyRequestActionEnum;
    /**
     * Optimistic Lock version
     * @type {number}
     * @memberof ClarifyRequest
     */
    'version': number;
    /**
     * 
     * @type {string}
     * @memberof ClarifyRequest
     */
    'englishName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClarifyRequest
     */
    'dataType'?: string;
    /**
     * 
     * @type {number}
     * @memberof ClarifyRequest
     */
    'dataLength'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClarifyRequest
     */
    'description'?: string;
}

export const ClarifyRequestActionEnum = {
    Define: 'DEFINE',
    Skip: 'SKIP'
} as const;

export type ClarifyRequestActionEnum = typeof ClarifyRequestActionEnum[keyof typeof ClarifyRequestActionEnum];

/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    'errorCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface PendingTermResponse
 */
export interface PendingTermResponse {
    /**
     * 
     * @type {number}
     * @memberof PendingTermResponse
     */
    'termId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PendingTermResponse
     */
    'koreanName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PendingTermResponse
     */
    'isComplete'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PendingTermResponse
     */
    'remainingCount'?: number;
}
/**
 * 
 * @export
 * @interface RequirementResponse
 */
export interface RequirementResponse {
    /**
     * 
     * @type {number}
     * @memberof RequirementResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof RequirementResponse
     */
    'requirementNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequirementResponse
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequirementResponse
     */
    'createdAt'?: string;
}

/**
 * AnalysisApi - axios parameter creator
 * @export
 */
export const AnalysisApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 통합 분석 결과 뷰어 조회
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RequirementsIdAnalysisViewGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1RequirementsIdAnalysisViewGet', 'id', id)
            const localVarPath = `/api/v1/requirements/{id}/analysis-view`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 완성된 데이터 사전을 바탕으로 Event Storming 요소들을 추출합니다.
         * @summary 요구사항 상세 Event Storming 분석 요청 (비동기)
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RequirementsIdAnalyzePost: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1RequirementsIdAnalyzePost', 'id', id)
            const localVarPath = `/api/v1/requirements/{id}/analyze`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AnalysisApi - functional programming interface
 * @export
 */
export const AnalysisApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AnalysisApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 통합 분석 결과 뷰어 조회
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1RequirementsIdAnalysisViewGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AnalysisViewResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1RequirementsIdAnalysisViewGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalysisApi.apiV1RequirementsIdAnalysisViewGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 완성된 데이터 사전을 바탕으로 Event Storming 요소들을 추출합니다.
         * @summary 요구사항 상세 Event Storming 분석 요청 (비동기)
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1RequirementsIdAnalyzePost(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AsyncJobResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1RequirementsIdAnalyzePost(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalysisApi.apiV1RequirementsIdAnalyzePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AnalysisApi - factory interface
 * @export
 */
export const AnalysisApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AnalysisApiFp(configuration)
    return {
        /**
         * 
         * @summary 통합 분석 결과 뷰어 조회
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RequirementsIdAnalysisViewGet(id: number, options?: RawAxiosRequestConfig): AxiosPromise<AnalysisViewResponse> {
            return localVarFp.apiV1RequirementsIdAnalysisViewGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 완성된 데이터 사전을 바탕으로 Event Storming 요소들을 추출합니다.
         * @summary 요구사항 상세 Event Storming 분석 요청 (비동기)
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RequirementsIdAnalyzePost(id: number, options?: RawAxiosRequestConfig): AxiosPromise<AsyncJobResponse> {
            return localVarFp.apiV1RequirementsIdAnalyzePost(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AnalysisApi - object-oriented interface
 * @export
 * @class AnalysisApi
 * @extends {BaseAPI}
 */
export class AnalysisApi extends BaseAPI {
    /**
     * 
     * @summary 통합 분석 결과 뷰어 조회
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public apiV1RequirementsIdAnalysisViewGet(id: number, options?: RawAxiosRequestConfig) {
        return AnalysisApiFp(this.configuration).apiV1RequirementsIdAnalysisViewGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 완성된 데이터 사전을 바탕으로 Event Storming 요소들을 추출합니다.
     * @summary 요구사항 상세 Event Storming 분석 요청 (비동기)
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApi
     */
    public apiV1RequirementsIdAnalyzePost(id: number, options?: RawAxiosRequestConfig) {
        return AnalysisApiFp(this.configuration).apiV1RequirementsIdAnalyzePost(id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DataDictionaryApi - axios parameter creator
 * @export
 */
export const DataDictionaryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 프로젝트 내 미정의(Undefine) 상태인 데이터 사전 용어 중 다음 명확화 대상 1건을 조회합니다.
         * @summary 미정의 용어 단건 조회
         * @param {string} projectName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProjectsProjectNameDataDictionaryPendingGet: async (projectName: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectName' is not null or undefined
            assertParamExists('apiV1ProjectsProjectNameDataDictionaryPendingGet', 'projectName', projectName)
            const localVarPath = `/api/v1/projects/{projectName}/data-dictionary/pending`
                .replace(`{${"projectName"}}`, encodeURIComponent(String(projectName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 기획자가 특정 용어에 대해 정의(DEFINE)를 수행하거나 건너뛰기(SKIP)를 선택합니다. 응답으로 즉시 다음 미정의 단어를 반환합니다.
         * @summary 단일 용어 명확화 제출 (인터랙션 피드백)
         * @param {string} projectName 
         * @param {number} termId 
         * @param {ClarifyRequest} clarifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost: async (projectName: string, termId: number, clarifyRequest: ClarifyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectName' is not null or undefined
            assertParamExists('apiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost', 'projectName', projectName)
            // verify required parameter 'termId' is not null or undefined
            assertParamExists('apiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost', 'termId', termId)
            // verify required parameter 'clarifyRequest' is not null or undefined
            assertParamExists('apiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost', 'clarifyRequest', clarifyRequest)
            const localVarPath = `/api/v1/projects/{projectName}/data-dictionary/{termId}/clarify`
                .replace(`{${"projectName"}}`, encodeURIComponent(String(projectName)))
                .replace(`{${"termId"}}`, encodeURIComponent(String(termId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(clarifyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 데이터 사전 자동 추출 요청 (비동기)
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RequirementsIdDataDictionaryExtractPost: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1RequirementsIdDataDictionaryExtractPost', 'id', id)
            const localVarPath = `/api/v1/requirements/{id}/data-dictionary/extract`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DataDictionaryApi - functional programming interface
 * @export
 */
export const DataDictionaryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DataDictionaryApiAxiosParamCreator(configuration)
    return {
        /**
         * 프로젝트 내 미정의(Undefine) 상태인 데이터 사전 용어 중 다음 명확화 대상 1건을 조회합니다.
         * @summary 미정의 용어 단건 조회
         * @param {string} projectName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ProjectsProjectNameDataDictionaryPendingGet(projectName: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PendingTermResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ProjectsProjectNameDataDictionaryPendingGet(projectName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DataDictionaryApi.apiV1ProjectsProjectNameDataDictionaryPendingGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 기획자가 특정 용어에 대해 정의(DEFINE)를 수행하거나 건너뛰기(SKIP)를 선택합니다. 응답으로 즉시 다음 미정의 단어를 반환합니다.
         * @summary 단일 용어 명확화 제출 (인터랙션 피드백)
         * @param {string} projectName 
         * @param {number} termId 
         * @param {ClarifyRequest} clarifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost(projectName: string, termId: number, clarifyRequest: ClarifyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost(projectName, termId, clarifyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DataDictionaryApi.apiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 데이터 사전 자동 추출 요청 (비동기)
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1RequirementsIdDataDictionaryExtractPost(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AsyncJobResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1RequirementsIdDataDictionaryExtractPost(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DataDictionaryApi.apiV1RequirementsIdDataDictionaryExtractPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DataDictionaryApi - factory interface
 * @export
 */
export const DataDictionaryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DataDictionaryApiFp(configuration)
    return {
        /**
         * 프로젝트 내 미정의(Undefine) 상태인 데이터 사전 용어 중 다음 명확화 대상 1건을 조회합니다.
         * @summary 미정의 용어 단건 조회
         * @param {string} projectName 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProjectsProjectNameDataDictionaryPendingGet(projectName: string, options?: RawAxiosRequestConfig): AxiosPromise<PendingTermResponse> {
            return localVarFp.apiV1ProjectsProjectNameDataDictionaryPendingGet(projectName, options).then((request) => request(axios, basePath));
        },
        /**
         * 기획자가 특정 용어에 대해 정의(DEFINE)를 수행하거나 건너뛰기(SKIP)를 선택합니다. 응답으로 즉시 다음 미정의 단어를 반환합니다.
         * @summary 단일 용어 명확화 제출 (인터랙션 피드백)
         * @param {string} projectName 
         * @param {number} termId 
         * @param {ClarifyRequest} clarifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost(projectName: string, termId: number, clarifyRequest: ClarifyRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost200Response> {
            return localVarFp.apiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost(projectName, termId, clarifyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 데이터 사전 자동 추출 요청 (비동기)
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RequirementsIdDataDictionaryExtractPost(id: number, options?: RawAxiosRequestConfig): AxiosPromise<AsyncJobResponse> {
            return localVarFp.apiV1RequirementsIdDataDictionaryExtractPost(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DataDictionaryApi - object-oriented interface
 * @export
 * @class DataDictionaryApi
 * @extends {BaseAPI}
 */
export class DataDictionaryApi extends BaseAPI {
    /**
     * 프로젝트 내 미정의(Undefine) 상태인 데이터 사전 용어 중 다음 명확화 대상 1건을 조회합니다.
     * @summary 미정의 용어 단건 조회
     * @param {string} projectName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataDictionaryApi
     */
    public apiV1ProjectsProjectNameDataDictionaryPendingGet(projectName: string, options?: RawAxiosRequestConfig) {
        return DataDictionaryApiFp(this.configuration).apiV1ProjectsProjectNameDataDictionaryPendingGet(projectName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 기획자가 특정 용어에 대해 정의(DEFINE)를 수행하거나 건너뛰기(SKIP)를 선택합니다. 응답으로 즉시 다음 미정의 단어를 반환합니다.
     * @summary 단일 용어 명확화 제출 (인터랙션 피드백)
     * @param {string} projectName 
     * @param {number} termId 
     * @param {ClarifyRequest} clarifyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataDictionaryApi
     */
    public apiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost(projectName: string, termId: number, clarifyRequest: ClarifyRequest, options?: RawAxiosRequestConfig) {
        return DataDictionaryApiFp(this.configuration).apiV1ProjectsProjectNameDataDictionaryTermIdClarifyPost(projectName, termId, clarifyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 데이터 사전 자동 추출 요청 (비동기)
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataDictionaryApi
     */
    public apiV1RequirementsIdDataDictionaryExtractPost(id: number, options?: RawAxiosRequestConfig) {
        return DataDictionaryApiFp(this.configuration).apiV1RequirementsIdDataDictionaryExtractPost(id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * RequirementsApi - axios parameter creator
 * @export
 */
export const RequirementsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 요구사항 상태 변경
         * @param {number} id 
         * @param {ApiV1RequirementsIdStatusPatchRequest} apiV1RequirementsIdStatusPatchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RequirementsIdStatusPatch: async (id: number, apiV1RequirementsIdStatusPatchRequest: ApiV1RequirementsIdStatusPatchRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1RequirementsIdStatusPatch', 'id', id)
            // verify required parameter 'apiV1RequirementsIdStatusPatchRequest' is not null or undefined
            assertParamExists('apiV1RequirementsIdStatusPatch', 'apiV1RequirementsIdStatusPatchRequest', apiV1RequirementsIdStatusPatchRequest)
            const localVarPath = `/api/v1/requirements/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiV1RequirementsIdStatusPatchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 마크다운 파일(.md)을 업로드하거나 텍스트를 직접 입력하여 요구사항을 등록합니다.
         * @summary 요구사항 등록
         * @param {string} data 요구사항 메타데이터 및 상세 텍스트 (JSON 문자열)
         * @param {File} [file] 마크다운(.md) 파일 (최대 10MB)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RequirementsPost: async (data: string, file?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('apiV1RequirementsPost', 'data', data)
            const localVarPath = `/api/v1/requirements`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
            if (data !== undefined) { 
                localVarFormParams.append('data', data as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RequirementsApi - functional programming interface
 * @export
 */
export const RequirementsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RequirementsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 요구사항 상태 변경
         * @param {number} id 
         * @param {ApiV1RequirementsIdStatusPatchRequest} apiV1RequirementsIdStatusPatchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1RequirementsIdStatusPatch(id: number, apiV1RequirementsIdStatusPatchRequest: ApiV1RequirementsIdStatusPatchRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiV1RequirementsIdStatusPatch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1RequirementsIdStatusPatch(id, apiV1RequirementsIdStatusPatchRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RequirementsApi.apiV1RequirementsIdStatusPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 마크다운 파일(.md)을 업로드하거나 텍스트를 직접 입력하여 요구사항을 등록합니다.
         * @summary 요구사항 등록
         * @param {string} data 요구사항 메타데이터 및 상세 텍스트 (JSON 문자열)
         * @param {File} [file] 마크다운(.md) 파일 (최대 10MB)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1RequirementsPost(data: string, file?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RequirementResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1RequirementsPost(data, file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RequirementsApi.apiV1RequirementsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RequirementsApi - factory interface
 * @export
 */
export const RequirementsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RequirementsApiFp(configuration)
    return {
        /**
         * 
         * @summary 요구사항 상태 변경
         * @param {number} id 
         * @param {ApiV1RequirementsIdStatusPatchRequest} apiV1RequirementsIdStatusPatchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RequirementsIdStatusPatch(id: number, apiV1RequirementsIdStatusPatchRequest: ApiV1RequirementsIdStatusPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiV1RequirementsIdStatusPatch200Response> {
            return localVarFp.apiV1RequirementsIdStatusPatch(id, apiV1RequirementsIdStatusPatchRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 마크다운 파일(.md)을 업로드하거나 텍스트를 직접 입력하여 요구사항을 등록합니다.
         * @summary 요구사항 등록
         * @param {string} data 요구사항 메타데이터 및 상세 텍스트 (JSON 문자열)
         * @param {File} [file] 마크다운(.md) 파일 (최대 10MB)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1RequirementsPost(data: string, file?: File, options?: RawAxiosRequestConfig): AxiosPromise<RequirementResponse> {
            return localVarFp.apiV1RequirementsPost(data, file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RequirementsApi - object-oriented interface
 * @export
 * @class RequirementsApi
 * @extends {BaseAPI}
 */
export class RequirementsApi extends BaseAPI {
    /**
     * 
     * @summary 요구사항 상태 변경
     * @param {number} id 
     * @param {ApiV1RequirementsIdStatusPatchRequest} apiV1RequirementsIdStatusPatchRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequirementsApi
     */
    public apiV1RequirementsIdStatusPatch(id: number, apiV1RequirementsIdStatusPatchRequest: ApiV1RequirementsIdStatusPatchRequest, options?: RawAxiosRequestConfig) {
        return RequirementsApiFp(this.configuration).apiV1RequirementsIdStatusPatch(id, apiV1RequirementsIdStatusPatchRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 마크다운 파일(.md)을 업로드하거나 텍스트를 직접 입력하여 요구사항을 등록합니다.
     * @summary 요구사항 등록
     * @param {string} data 요구사항 메타데이터 및 상세 텍스트 (JSON 문자열)
     * @param {File} [file] 마크다운(.md) 파일 (최대 10MB)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequirementsApi
     */
    public apiV1RequirementsPost(data: string, file?: File, options?: RawAxiosRequestConfig) {
        return RequirementsApiFp(this.configuration).apiV1RequirementsPost(data, file, options).then((request) => request(this.axios, this.basePath));
    }
}



